apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 512;
    }
    http {
      sendfile on;
      tcp_nopush on;
      keepalive_timeout 15s;
      client_body_buffer_size 4k;
      client_max_body_size 1m;
      access_log off;
      error_log /var/log/nginx/error.log warn;

      upstream http_servers {
        server 2pc-transfer-http:50051;
      }

      server {
        listen 80;
        location / {
          proxy_pass http://http_servers;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
