kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: accounts
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: accounts
subjects:
  # Uses the default service account. Consider creating a new one.
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: accounts
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app.kubernetes.io/name: accounts
    app.kubernetes.io/component: AccountsSystem
    app.kubernetes.io/part-of: Sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: accounts
      app.kubernetes.io/component: AccountsSystem
      app.kubernetes.io/part-of: Sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: accounts
        app.kubernetes.io/component: AccountsSystem
        app.kubernetes.io/part-of: Sample
    spec:
      containers:
        - name: accounts
          image: "accounts:dev-k8s"
          command: ["./accounts", "run"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
            - containerPort: 50052
              name: remoting-port
              protocol: TCP
            - containerPort: 3322
              name: discovery-port
              protocol: TCP
            - containerPort: 3320
              name: peers-port
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DISCOVERY_PORT
              value: "3322"
            - name: PEERS_PORT
              value: "3320"
            - name: REMOTING_PORT
              value: "50052"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app.kubernetes.io/name: accounts
    app.kubernetes.io/component: AccountsSystem
    app.kubernetes.io/part-of: Sample
spec:
  selector:
    app.kubernetes.io/name: accounts
    app.kubernetes.io/component: AccountsSystem
    app.kubernetes.io/part-of: Sample
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50051
      targetPort: grpc
      name: grpc
