// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sample/service.proto

package samplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateAccount *CreateAccount         `protobuf:"bytes,1,opt,name=create_account,json=createAccount,proto3" json:"create_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_sample_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_sample_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetCreateAccount() *CreateAccount {
	if x != nil {
		return x.CreateAccount
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_sample_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_sample_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreditAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditAccount *CreditAccount         `protobuf:"bytes,1,opt,name=credit_account,json=creditAccount,proto3" json:"credit_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditAccountRequest) Reset() {
	*x = CreditAccountRequest{}
	mi := &file_sample_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountRequest) ProtoMessage() {}

func (x *CreditAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountRequest.ProtoReflect.Descriptor instead.
func (*CreditAccountRequest) Descriptor() ([]byte, []int) {
	return file_sample_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreditAccountRequest) GetCreditAccount() *CreditAccount {
	if x != nil {
		return x.CreditAccount
	}
	return nil
}

type CreditAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditAccountResponse) Reset() {
	*x = CreditAccountResponse{}
	mi := &file_sample_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountResponse) ProtoMessage() {}

func (x *CreditAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountResponse.ProtoReflect.Descriptor instead.
func (*CreditAccountResponse) Descriptor() ([]byte, []int) {
	return file_sample_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreditAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_sample_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sample_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_sample_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_sample_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sample_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_sample_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_sample_service_proto protoreflect.FileDescriptor

const file_sample_service_proto_rawDesc = "" +
	"\n" +
	"\x14sample/service.proto\x12\bsamplepb\x1a\x13sample/sample.proto\"V\n" +
	"\x14CreateAccountRequest\x12>\n" +
	"\x0ecreate_account\x18\x01 \x01(\v2\x17.samplepb.CreateAccountR\rcreateAccount\"D\n" +
	"\x15CreateAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.samplepb.AccountR\aaccount\"V\n" +
	"\x14CreditAccountRequest\x12>\n" +
	"\x0ecredit_account\x18\x01 \x01(\v2\x17.samplepb.CreditAccountR\rcreditAccount\"D\n" +
	"\x15CreditAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.samplepb.AccountR\aaccount\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"A\n" +
	"\x12GetAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.samplepb.AccountR\aaccount2\xfd\x01\n" +
	"\x0eAccountService\x12P\n" +
	"\rCreateAccount\x12\x1e.samplepb.CreateAccountRequest\x1a\x1f.samplepb.CreateAccountResponse\x12P\n" +
	"\rCreditAccount\x12\x1e.samplepb.CreditAccountRequest\x1a\x1f.samplepb.CreditAccountResponse\x12G\n" +
	"\n" +
	"GetAccount\x12\x1b.samplepb.GetAccountRequest\x1a\x1c.samplepb.GetAccountResponseB\xa0\x01\n" +
	"\fcom.samplepbB\fServiceProtoH\x02P\x01Z@github.com/tochemey/goakt-examples/v2/internal/samplepb;samplepb\xa2\x02\x03SXX\xaa\x02\bSamplepb\xca\x02\bSamplepb\xe2\x02\x14Samplepb\\GPBMetadata\xea\x02\bSamplepbb\x06proto3"

var (
	file_sample_service_proto_rawDescOnce sync.Once
	file_sample_service_proto_rawDescData []byte
)

func file_sample_service_proto_rawDescGZIP() []byte {
	file_sample_service_proto_rawDescOnce.Do(func() {
		file_sample_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_service_proto_rawDesc), len(file_sample_service_proto_rawDesc)))
	})
	return file_sample_service_proto_rawDescData
}

var file_sample_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sample_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: samplepb.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: samplepb.CreateAccountResponse
	(*CreditAccountRequest)(nil),  // 2: samplepb.CreditAccountRequest
	(*CreditAccountResponse)(nil), // 3: samplepb.CreditAccountResponse
	(*GetAccountRequest)(nil),     // 4: samplepb.GetAccountRequest
	(*GetAccountResponse)(nil),    // 5: samplepb.GetAccountResponse
	(*CreateAccount)(nil),         // 6: samplepb.CreateAccount
	(*Account)(nil),               // 7: samplepb.Account
	(*CreditAccount)(nil),         // 8: samplepb.CreditAccount
}
var file_sample_service_proto_depIdxs = []int32{
	6, // 0: samplepb.CreateAccountRequest.create_account:type_name -> samplepb.CreateAccount
	7, // 1: samplepb.CreateAccountResponse.account:type_name -> samplepb.Account
	8, // 2: samplepb.CreditAccountRequest.credit_account:type_name -> samplepb.CreditAccount
	7, // 3: samplepb.CreditAccountResponse.account:type_name -> samplepb.Account
	7, // 4: samplepb.GetAccountResponse.account:type_name -> samplepb.Account
	0, // 5: samplepb.AccountService.CreateAccount:input_type -> samplepb.CreateAccountRequest
	2, // 6: samplepb.AccountService.CreditAccount:input_type -> samplepb.CreditAccountRequest
	4, // 7: samplepb.AccountService.GetAccount:input_type -> samplepb.GetAccountRequest
	1, // 8: samplepb.AccountService.CreateAccount:output_type -> samplepb.CreateAccountResponse
	3, // 9: samplepb.AccountService.CreditAccount:output_type -> samplepb.CreditAccountResponse
	5, // 10: samplepb.AccountService.GetAccount:output_type -> samplepb.GetAccountResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sample_service_proto_init() }
func file_sample_service_proto_init() {
	if File_sample_service_proto != nil {
		return
	}
	file_sample_sample_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_service_proto_rawDesc), len(file_sample_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sample_service_proto_goTypes,
		DependencyIndexes: file_sample_service_proto_depIdxs,
		MessageInfos:      file_sample_service_proto_msgTypes,
	}.Build()
	File_sample_service_proto = out.File
	file_sample_service_proto_goTypes = nil
	file_sample_service_proto_depIdxs = nil
}
