//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2. DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// Account defines model for Account.
type Account struct {
	AccountBalance float64 `json:"account_balance"`
	AccountId      string  `json:"account_id"`
}

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	Account Account `json:"account"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	CreateAccount struct {
		AccountBalance float64 `json:"account_balance"`
		AccountId      string  `json:"account_id"`
	} `json:"create_account"`
}

// CreditAccountRequest defines model for CreditAccountRequest.
type CreditAccountRequest struct {
	Amount float64 `json:"amount"`
}

// CreateTransferRequest defines model for CreateTransferRequest.
type CreateTransferRequest struct {
	Transfer struct {
		FromAccountId string  `json:"from_account_id"`
		ToAccountId   string  `json:"to_account_id"`
		Amount        float64 `json:"amount"`
	} `json:"transfer"`
}

// TransferResponse defines model for TransferResponse.
type TransferResponse struct {
	Transfer struct {
		TransferId string  `json:"transfer_id"`
		Status     string  `json:"status"`
		Reason     *string `json:"reason,omitempty"`
	} `json:"transfer"`
}

// TransferStatusResponse defines model for TransferStatusResponse.
type TransferStatusResponse struct {
	Transfer struct {
		TransferId string  `json:"transfer_id"`
		Status     string  `json:"status"`
		Reason     *string `json:"reason,omitempty"`
	} `json:"transfer"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	CreateAccount(w http.ResponseWriter, r *http.Request)
	GetAccount(w http.ResponseWriter, r *http.Request, accountId string)
	CreditAccount(w http.ResponseWriter, r *http.Request, accountId string)
	CreateTransfer(w http.ResponseWriter, r *http.Request)
	GetTransfer(w http.ResponseWriter, r *http.Request, transferId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))
	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}
	handler.ServeHTTP(w, r)
}

func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {
	var accountId string
	err := runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountId)
	}))
	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}
	handler.ServeHTTP(w, r)
}

func (siw *ServerInterfaceWrapper) CreditAccount(w http.ResponseWriter, r *http.Request) {
	var accountId string
	err := runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreditAccount(w, r, accountId)
	}))
	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}
	handler.ServeHTTP(w, r)
}

func (siw *ServerInterfaceWrapper) CreateTransfer(w http.ResponseWriter, r *http.Request) {
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTransfer(w, r)
	}))
	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}
	handler.ServeHTTP(w, r)
}

func (siw *ServerInterfaceWrapper) GetTransfer(w http.ResponseWriter, r *http.Request) {
	var transferId string
	err := runtime.BindStyledParameterWithOptions("simple", "transferId", r.PathValue("transferId"), &transferId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transferId", Err: err})
		return
	}
	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransfer(w, r, transferId)
	}))
	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}
	handler.ServeHTTP(w, r)
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{BaseRouter: m})
}

func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter
	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}
	m.HandleFunc("POST "+options.BaseURL+"/accounts", wrapper.CreateAccount)
	m.HandleFunc("GET "+options.BaseURL+"/accounts/{accountId}", wrapper.GetAccount)
	m.HandleFunc("POST "+options.BaseURL+"/accounts/{accountId}/credit", wrapper.CreditAccount)
	m.HandleFunc("POST "+options.BaseURL+"/transfers", wrapper.CreateTransfer)
	m.HandleFunc("GET "+options.BaseURL+"/transfers/{transferId}", wrapper.GetTransfer)
	return m
}
