apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: goakt_ai
  POSTGRES_PASSWORD: goakt_ai
  POSTGRES_DB: goakt_ai
